### ISSUE TITLE
run failure with cosmosdb example

### ISSUE THREAD

**Issue by foxundermoon** [nestjs/azure-database#155]
```bash
pwd
.../azure-database/sample/cosmos-db

npm i
npm run build
npm run start

```

```

> cosmos-db@0.0.1 start /Volumes/data/workspace/draft/azure-db/azure-database/sample/cosmos-db
> nest start

[Nest] 72867   - 04/13/2020, 1:04:02 AM   [NestFactory] Starting Nest application...
[Nest] 72867   - 04/13/2020, 1:04:02 AM   [InstanceLoader] AppModule dependencies initialized +17ms
[Nest] 72867   - 04/13/2020, 1:04:02 AM   [InstanceLoader] AzureCosmosDbModule dependencies initialized +1ms
[Nest] 72867   - 04/13/2020, 1:04:02 AM   [ExceptionHandler] Nest can't resolve dependencies of the ContactService (?). Please make sure that the argument ContactRepository at index [0] is available in the ContactModule context.

Potential solutions:
- If ContactRepository is a provider, is it part of the current ContactModule?
- If ContactRepository is exported from a separate @Module, is that module imported within ContactModule?
  @Module({
    imports: [ /* the Module containing ContactRepository */ ]
  })
 +1ms
Error: Nest can't resolve dependencies of the ContactService (?). Please make sure that the argument ContactRepository at index [0] is available in the ContactModule context.

Potential solutions:
- If ContactRepository is a provider, is it part of the current ContactModule?
- If ContactRepository is exported from a separate @Module, is that module imported within ContactModule?
  @Module({
    imports: [ /* the Module containing ContactRepository */ ]
  })

    at Injector.lookupComponentInParentModules (/Volumes/data/workspace/draft/azure-db/azure-database/sample/cosmos-db/node_modules/@nestjs/core/injector/injector.js:191:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Injector.resolveComponentInstance (/Volumes/data/workspace/draft/azure-db/azure-database/sample/cosmos-db/node_modules/@nestjs/core/injector/injector.js:147:33)
    at async resolveParam (/Volumes/data/workspace/draft/azure-db/azure-database/sample/cosmos-db/node_modules/@nestjs/core/injector/injector.js:101:38)
    at async Promise.all (index 0)
    at async Injector.resolveConstructorParams (/Volumes/data/workspace/draft/azure-db/azure-database/sample/cosmos-db/node_modules/@nestjs/core/injector/injector.js:116:27)
    at async Injector.loadInstance (/Volumes/data/workspace/draft/azure-db/azure-database/sample/cosmos-db/node_modules/@nestjs/core/injector/injector.js:80:9)
    at async Injector.loadProvider (/Volumes/data/workspace/draft/azure-db/azure-database/sample/cosmos-db/node_modules/@nestjs/core/injector/injector.js:37:9)
    at async Promise.all (index 3)
    at async InstanceLoader.createInstancesOfProviders (/Volumes/data/workspace/draft/azure-db/azure-database/sample/cosmos-db/node_modules/@nestjs/core/injector/instance-loader.js:42:9)
```
## Environment

```
node -v
v12.16.2

 npm -v
6.14.4

macos 10.14.6

```

**Comment by benjamin79** [comment]
@foxundermoon Have the same error. How did you solve it?

**Comment by tomjdickson** [comment]
> @foxundermoon Have the same error. How did you solve it?

Did you end up figuring it out Ben?

**Comment by bm77525-kr** [comment]
Also having the same issue. Anyone figure this out?

**Comment by tomjdickson** [comment]
> Also having the same issue. Anyone figure this out?

I ended up just using the Mongo API in COSMOS with nestjs/mongoose & mongoose.
